apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: backstage-templates
spec:
  type: url
  targets:
    - https://github.com/rdurelli/backstage-templates/blob/main/java-basic/template.yaml