apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: Projeto Java básico criado via Backstage
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner | dump }}
